spring.application.name=librivoxis

# Conexão com PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/librivoxis
spring.datasource.username=user
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=3000
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true