spring.application.name=librivoxis

# Conexão com PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/librivoxis
spring.datasource.username=postgres
spring.datasource.password=7160
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true